import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import products from "../data/products.json";
import categories from "../data/categories.json";
import banners from "../data/banner.json";
import bestSellers from "../data/bestSellingProducts.json";
import Contacts from "../data/contact.json";
import Categories from "../components/Categories";
import HeroSection from "../components/HeroSection";
import ProductSection from "../components/ProductSection";
import {
  BannerElement,
  BestSellingProduct,
  Category,
  Contact,
  Product,
} from "../types";
import BannerSection from "../components/BannerSection";
import DailySells from "../components/DailySells";
import TopRatedProducts from "../components/TopRatedProducts";
import DealSection from "../components/DealSection";
import Footer from "../components/Footer";
import FooterEndLine from "../layouts/FooterEndLine";

interface IDataProps {
  products: Product[];
  categories: Category[];
  banners: BannerElement[];
  bestSellers: BestSellingProduct[];
  contact: Contact[];
}

const Home: NextPage<IDataProps> = ({
  products,
  categories,
  banners,
  bestSellers,
  contact,
}) => {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <HeroSection />
      <Categories categories={categories} />
      <ProductSection products={products} />
      <BannerSection banners={banners} />
      <DailySells bestSellers={bestSellers} />
      <TopRatedProducts categories={categories} />
      <DealSection />
      <Footer contact={contact} />
      <FooterEndLine />
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      products: products.products,
      categories: categories.categories,
      banners: banners.banners,
      bestSellers: bestSellers.BestSellingProducts,
      contact: Contacts.contact,
    },
  };
};
